apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: drebo2324/ms-frontend:latest
          ports:
            #NGINX DEFAULT PORT
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    #NGINX DEFAULT PORT
    - protocol: TCP
      port: 80
      targetPort: 80