apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:9.0
          name: mysql
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
            - valueFrom:
                secretKeyRef:
                  key: mysql_root_password
                  name: mysql-secrets
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-data #must match volumes name
            - mountPath: /docker-entrypoint-initdb.d/init.sql
              name: mysql-initdb-config #configMap name
      volumes:
        - name: mysql-data #must match volumesMounts
          persistentVolumeClaim:
            claimName: mysql-pvc
        - name: mysql-initdb-config
          configMap:
            name: mysql-initdb-config

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  ports:
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: mysql

---
apiVersion: v1
data:
  mysql_root_password: RG9zdG9ldnNreTIzMjQ=
kind: Secret
metadata:
  name: mysql-secrets

---
apiVersion: v1
kind: PersistenceVolume
metadata:
  name: mysql-pv
specs:
  storageClassName: 'standard'
  accessMode:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/mysql

---
apiVersion: v1
kind: PersistenceVolumeClaim
metadata:
  name: mysql-pvc
specs:
  storageClassName: 'standard'
  accessMode:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  initdb.sql: |
    CREATE DATABASE IF NOT EXISTS order_service;
    CREATE DATABASE IF NOT EXISTS inventory_service;
    
